footprint: [[0.20,0.20],[0.20,-0.20],[-0.20,-0.20],[-0.20,0.20]]
obstacle_range: 10.0
raytrace_range: 10.5

inflation_radius: 0.5
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: camera_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}