global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 3.0
  static_map: true
  always_send_full_costmap: true
  observation_sources: laser_scan_sensor
  point_cloud_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
  plugins:
     - {name: static_layer, type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
